### ISSUE TITLE
Website list to add

### ISSUE THREAD

**Issue by lefouetteur** [Anto-Napo/work-site-block-firefox#1]
https://pornhub.com
https://fr.y8.com/
https://www.crazygames.fr/
https://www.kodub.com/apps/polytrack
https://shellshock.io/
https://games.voodoo.io/paperio2
https://neal.fun/
https://doodlejump.io/
https://www.scan-manga.com/?po
https://www.jeux.fr/
https://www.1001jeux.fr/
https://www.jeuxjeux.fr/
https://kekma.net/
https://brawltime.ninja/fr/
https://brawlstats.com/
https://www.smbgames.be/
https://supermarioplay.com/

**Comment by lefouetteur** [comment]
this list is very nice!
Great Job!

**Comment by Anto-Napo** [comment]
Done :+1:
